# Tensorflow 2 quickstart for beginners

Set up TensorFlow

In [1]:
import tensorflow as tf
print("Tensorflow version: ", tf.__version__)

Tensorflow version:  2.11.0


Load a dataset

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 3s 0us/step


Build a machine learning model

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.6673723 , -0.34112465, -0.2384841 ,  0.35469508, -0.38024336,
         0.3218733 , -0.16823065,  0.30567706,  0.4233381 ,  0.2340164 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.16337235, 0.05959281, 0.06603438, 0.11950459, 0.05730663,
        0.1156459 , 0.07084037, 0.11378796, 0.12799585, 0.10591915]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.1572223

In [8]:
model.compile(optimizer='adam',
            loss=loss_fn,
            metrics=['accuracy'])

Train and evaluate your model

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.2934 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1429 - accuracy: 0.9583
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1075 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0870 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0743 - accuracy: 0.9765


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 2s - loss: 0.0717 - accuracy: 0.9781 - 2s/epoch - 6ms/step


[0.07166684418916702, 0.9781000018119812]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.0665833e-11, 1.3051534e-09, 1.3174872e-06, 5.3949120e-06,
        2.3403357e-11, 2.3930848e-08, 6.3428300e-14, 9.9999249e-01,
        2.7425498e-08, 8.1906040e-07],
       [2.7636696e-10, 1.5525760e-04, 9.9984455e-01, 6.7035053e-08,
        4.0594798e-16, 9.2187963e-10, 1.1521930e-08, 9.0197934e-16,
        1.2277864e-07, 8.8944551e-14],
       [8.0425696e-07, 9.9698251e-01, 5.0105690e-04, 4.0917090e-05,
        3.0214956e-04, 1.2646376e-05, 1.8213124e-05, 1.1121788e-03,
        9.7365520e-04, 5.5967637e-05],
       [9.9983537e-01, 7.6315387e-10, 1.3511034e-04, 2.3282006e-08,
        7.9130629e-08, 1.6495253e-06, 2.5849096e-05, 1.0415824e-06,
        8.7293252e-08, 7.4570909e-07],
       [2.0030523e-06, 4.0412569e-11, 8.2343076e-06, 1.5564336e-07,
        9.8353231e-01, 5.2158236e-07, 4.6935190e-07, 1.2946028e-04,
        1.3724386e-07, 1.6326772e-02]], dtype=float32)>